## Machine Learning - Session 1 - NumPy

In [1]:
#Import the numpy library
import numpy as np

#### A. Defining a 1D numpy array

In [2]:
l = [12,34,56,7]

In [3]:
type(l)

list

In [4]:
x = np.array(l)
x

array([12, 34, 56,  7])

In [5]:
type(x)

numpy.ndarray

In [5]:
k = [1,'e']
j = np.array(k)
type(j)

numpy.ndarray

In [6]:
j

array(['1', 'e'], dtype='<U11')

In [7]:
j.dtype #it is now changed to all as string only

dtype('<U11')

In [8]:
print(j) # changed to str all 

['1' 'e']


#### B. Creating Regular Sequence

In [5]:
#Create a regular sequence of integers starting from 1 to 10. integers = c(1,2,3,4,.......,10)
i = np.arange(1,11)
print(i)
j = np.arange(1,11,1)
print(j)
j


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#Create a regular sequence of integers starting from 10 to 1.
i = np.arange(10,0,-1)
i


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
#Create a regular sequence of even integers between 10 to 20
i = np.arange(10,21,1)
i


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
#Create a regular sequence of the following type: [10.0,10.5,11.0,11.5, ... , 19.5, 20.0]
i = np.arange(10.0,20.5,0.5)
i
i.dtype

dtype('float64')

In [17]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [19]:
#Create a regular sequence of length 20 ranging from 0 to 5
np.linspace(start = 0, stop = 5, num = 20, endpoint = False)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

In [7]:
#Create a regular sequence of length 20 ranging from 0 to 5
np.linspace(start = 1, stop = 5, num = 20, endpoint = True, retstep=True)


(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [ ]:
#Help for np.linspace

help(np.linspace)

In [ ]:
#Studying the arange function

help(np.arange)

#### C. Creating a Random Sequence

In [18]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [36]:
#Generate 20 random numbers between 1 and 100
#random is a part of numpy
np.random.seed(0) #if 
np.random.randint(1,10,20) # 1 to 100 and give  only 20 nos.


array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8, 7, 9, 9, 2, 7, 8, 8, 9, 2, 6])

In [37]:
#Generate 20 random numbers between 1 and 100
#random is a part of numpy
np.random.seed(533) #seed is fixed random for each number (any number).
np.random.randint(1,100,20)


array([69, 93, 26, 23, 19, 11, 56, 69, 67, 29, 17, 92, 33, 68, 94, 54, 66,
       38, 35, 45])

In [40]:
#Generate 20 random numbers between 1 and 100
#random is a part of numpy
#np.random.seed(53) #if no seed, every time u run , it will give diff outputs. randomly
np.random.randint(1,100,20)


array([27, 47, 82, 17, 86, 73, 90, 94, 61, 62, 81, 64, 70, 18,  3, 73, 17,
       55, 25, 73])

In [48]:
#Shuffle the vector x
l = [12,23,34,45,56,67]
x = np.array(l)
#np.random.seed(0) we can use seed also to fix the shuffle one time
np.random.shuffle(x) #it returns none.
x #shuffled x randomly eah time u runs

array([23, 45, 56, 12, 34, 67])

In [50]:
#Permute x and return it
x


array([23, 45, 56, 12, 34, 67])

In [51]:
x

array([23, 45, 56, 12, 34, 67])

In [9]:
z = np.random.randn(10)
z

array([-1.35835993,  0.23334462,  0.81864185,  0.19255588,  1.3863969 ,
        0.13110427, -0.79020661, -0.1923827 , -1.38526034, -1.10583456])

In [12]:
y = np.random.randint(10,size=10)
y

array([4, 9, 2, 4, 8, 2, 5, 3, 8, 9])

In [52]:
#if we want to randomly select few from x: (fr a sample)
np.random.choice(x, 4, replace = False) # if replace is false, without replacement. it is recommended..
#(input variable, no of elements to be selected and it shouldnt greater than len of input, replace = bool value)


array([12, 67, 45, 56])

In [55]:
np.random.choice(x, 15) # by default it is true , it will return with rep

array([23, 45, 12, 67, 12, 12, 23, 45, 45, 45, 23, 56, 34, 12, 12])

To find more on numpy random sampling Go To this link 
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html 

#### D. Some basic numpy methods

In [13]:
x = np.array([12,34,24,45,7,18])

In [14]:
#Size of the array
x.size

6

In [58]:
#data type
x.dtype

dtype('int32')

In [60]:
#Type of the object
type(x)

numpy.ndarray

True

In [63]:
#Type conversion
x.astype(str) 

array(['12', '34', '24', '45', '7', '18'], dtype='<U11')

In [64]:
x.astype(float)

array([12., 34., 24., 45.,  7., 18.])

In [65]:
y = np.array([11.2, 23.21, 3.2, 5.99])
y

array([11.2 , 23.21,  3.2 ,  5.99])

In [66]:
y.astype(str)

array(['11.2', '23.21', '3.2', '5.99'], dtype='<U32')

In [67]:
y.astype(int)

array([11, 23,  3,  5])

#### E. Some basic (1D) numpy operations

In [68]:
#Consider that we have two arrays of same size.

x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [77]:
#Addition
x + y

array([15, 40, 32, 50,  8, 28])

In [78]:
#Subtraction
x - y

array([ 9, 28, 16, 40,  6,  8])

In [72]:
#Multiplication by scalar
x*y

array([ 36, 204, 192, 225,   7, 180])

In [73]:
np.sum(x+y)

173

In [74]:
#Element wise multiplication (dot product)
np.sum(x*y)

844

In [75]:
#Using dot method (i.e., sum of all multiplied )
np.dot(x,y)

844

In [76]:
x.dot(y)

844

In [81]:
y.dot(x)

844

In [88]:
#Squaring each elements in an array #very fast than for loop.
x**(1/2)


array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [87]:
x

array([12, 34, 24, 45,  7, 18])

In [91]:
np.sqrt(x)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [94]:
np.log(x)

array([2.48490665, 3.52636052, 3.17805383, 3.80666249, 1.94591015,
       2.89037176])

In [95]:
np.exp(x)

array([1.62754791e+05, 5.83461743e+14, 2.64891221e+10, 3.49342711e+19,
       1.09663316e+03, 6.56599691e+07])

In [97]:
type(x)

numpy.ndarray

#### F. Some Useful Numpy Functions

In [15]:
y = np.array([3,6,8,5,1,10])
y

array([ 3,  6,  8,  5,  1, 10])

In [16]:
#Sum
np.sum(y)

33

In [17]:
y.sum()

33

In [104]:
#Mean
np.mean(y)

5.5

In [105]:
np.median(y)

5.5

In [106]:
np.mode(y)

AttributeError: module 'numpy' has no attribute 'mode'

In [107]:
#Standard Deviation
np.std(y)

2.9860788111948193

In [18]:
y.std()

2.9860788111948193

In [91]:
#Minimum
np.min(y)

1

In [92]:
#Maximum
np.max(y)

10

In [94]:
#Percentiles
np.percentile(y,25)

3.5

In [95]:
np.percentile(y,[25,50,75]) #percentiles multilpe as list.

array([3.5, 5.5, 7.5])

In [20]:
#Sorting
np.sort(y)

array([ 1,  3,  5,  6,  8, 10])

In [25]:
y

array([ 3,  6,  8,  5,  1, 10])

In [103]:
np.sort(-y)

array([-10,  -8,  -6,  -5,  -3,  -1])

In [104]:
-np.sort(y)

array([ -1,  -3,  -5,  -6,  -8, -10])

In [26]:
-np.sort(-y)

array([10,  8,  6,  5,  3,  1])

AxisError: axis 1 is out of bounds for array of dimension 1

#### G. Subsetting a 1D numpy array

In [109]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [110]:
#Subsetting and slicing is same as list
x[4]

7

In [111]:
y[2:5]

array([8, 5, 1])

In [112]:
x[::-1]

array([18,  7, 45, 24, 34, 12])

In [113]:
y[[2,4]] #2nd and 4th element, pass as a list

array([8, 1])

In [115]:
x[[1,5,-1]]

array([34, 18, 18])

#### H. Conditional Subsetting

**The Comparison Operators**

      > is greater than
      < is less than
      == is equal to
      <= is less than equal to
      >= is greater than equal to

In [117]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [118]:
2 > 10

False

In [119]:
x > 10

array([ True,  True,  True,  True, False,  True])

In [120]:
y <=5

array([ True, False, False,  True,  True, False])

In [126]:
(y == 1).dtype

dtype('bool')

In [122]:
sum(y<=5) #count of no of trues.

3

**The Logical Operators**

    AND: &
    OR : |

In [127]:
(x>20) | (x<10)

array([False,  True,  True,  True,  True, False])

In [130]:
(x>10) & (x<20)

array([ True, False, False, False, False,  True])

**Problems**

In [33]:
#Consider the following two vectors

x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

In [34]:
#a. Vaues of x that are less than 35
x[x < 35] #returns np array of only True related values


array([33, 23])

In [35]:
#b. The number of observations in y that are more than 150
sum(y>150)


2

In [137]:
#OR
y[(y<120)|(y>160)]

array([108, 164, 119])

In [36]:
#c. The number of observations in y that are between 120 and 160
sum((y>=120) & (y<=160))

3

In [141]:
#d. The vaues in x that are less than 30 or greater than 50
x[(x<30)|(x>50)]

array([23, 67, 54])

In [144]:
#e. The values in x for which the values in y is less than or equal to 120
x[(y<=120)]

array([33, 67])

In [145]:
#f. The values in y for which the values in x is equal to 45
y[(x == 45)]

array([151])

#### I. Defining a 2D numpy array

In [37]:
#Converting a 1D array into 2D array
x = np.array([33,45,23,67,54,48])

matrix = x.reshape(2,3) #2 rows 2 columns
matrix

array([[33, 45, 23],
       [67, 54, 48]])

In [152]:
m = x.reshape(6,1)
m

array([[33],
       [45],
       [23],
       [67],
       [54],
       [48]])

In [153]:
m = x.reshape(3,2)
m

array([[33, 45],
       [23, 67],
       [54, 48]])

In [41]:
h = y.reshape(2,3)
h

array([[108, 151, 164],
       [119, 135, 122]])

In [154]:
#Create a 3x3 matrix containing elements from 1 to 9

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
#Joining two 1D arrays to form a matrix
x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

m = np.array([x, y])
m


array([[ 33,  45,  23,  67,  54,  48],
       [108, 151, 164, 119, 135, 122]])

#### J. Some basic methods for 2D numpy array

In [43]:
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [44]:
#Checking the shape of the matrix
matrix.shape

(5, 3)

In [45]:
#Dimension of the array
matrix.ndim

2

In [48]:
#Data type of the elements in the array
matrix.dtype

dtype('int32')

In [49]:
matrix.astype('float32')

array([[38., 33., 47.],
       [29., 48., 35.],
       [21., 34., 47.],
       [38., 44., 21.],
       [28., 26., 43.]], dtype=float32)

In [50]:
matrix.size

15

In [164]:
#Number of elements present in the matrix
matrix.size

15

In [54]:
#Size of the matrix in bytes
matrix.astype('str').itemsize

44

#### K. Subsetting 2D numpy array

In [217]:
#matrix
matrix


array([[24, 24, 24],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 30]])

In [167]:
#a) Print the first element of the matrix.
matrix[0,0]


38

In [168]:
#b) Print the last element of the matrix.
matrix[4,2]

43

In [182]:
#Or
matrix[4][2]

43

In [179]:
#c) Print the values of the first row.
matrix[0]

array([38, 33, 47])

In [180]:
#d) Print the values of the fourth row.
matrix[-1][:]

array([28, 26, 43])

In [181]:
#e) Print the values first column.
matrix[:,0]

array([38, 29, 21, 38, 28])

In [55]:
#f) Calculate the total of the third row.
np.sum(matrix[2])

102

In [56]:
#g) Calculate the total of the fifth row.
np.sum(matrix[4])

97

In [57]:
#h) Calculate the total of the second column.
np.sum(matrix[:,1])

185

In [58]:
#i) Calculate the average of the values of the first row.
np.mean(matrix[0])

39.333333333333336

In [59]:
#j) Replace the first value of the matrix by 50.
matrix[0,0] = 50
matrix



array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [197]:
#k) Replace the last value of the matrix by 30.
matrix[-1,-1] = 30
matrix


array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 30]])

In [62]:
#l) Replace the second column of the matrix by the vector (20,30,20,30,20)
matrix[:,1] = (20,30,20,30,20)
matrix


array([[24, 20, 24],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 43]])

In [63]:
#m) Replace the first row of the matrix by the vector its average (calculated above).
matrix[0,0] = np.mean(matrix[:,1])
matrix



array([[24, 20, 24],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 43]])

In [64]:
#q) Calculate the sum of all the elements of the matrix
sum(sum(matrix))


430

In [65]:
np.sum(matrix) #always use this

430

In [66]:
#r) Calculate the sum of all the rows on the matrix
np.sum(matrix,axis = 1)


array([68, 94, 88, 89, 91])

In [67]:
np.sum(matrix, axis=1)

array([68, 94, 88, 89, 91])

In [68]:
#s) Calculate the sum of all the colummns of the matrix
sum(matrix) #defult is sum of columns only


array([140, 120, 170])

In [69]:
np.sum(matrix, axis = 0)

array([140, 120, 170])

#### L. Matrix Operations

In [70]:
#Defining a matrix 'm'
m = np.array([[2,3],[4,5]])
m

array([[2, 3],
       [4, 5]])

In [71]:
#Defining a matrix 'n'
n = np.array([[1,0],[3,6]])
n

array([[1, 0],
       [3, 6]])

In [72]:
#Multiplication by scalar
2*n

array([[ 2,  0],
       [ 6, 12]])

In [73]:
#Matrix addition
m+n

array([[ 3,  3],
       [ 7, 11]])

In [74]:
#Matrix Multilication
np.dot(m,n)

array([[11, 18],
       [19, 30]])

In [235]:
#Preferred - for Matrix Multilication
np.matmul(m,n)

array([[11, 18],
       [19, 30]])

In [75]:
#Preferred - for Matrix Multilication
m @ n

array([[11, 18],
       [19, 30]])

In [77]:
m,n

(array([[2, 3],
        [4, 5]]), array([[1, 0],
        [3, 6]]))

In [76]:
#Element-wise array multilication
np.multiply(m,n)

array([[ 2,  0],
       [12, 30]])

In [238]:
m*n #this is ------

array([[ 2,  0],
       [12, 30]])

#### Copying data

In [78]:
p = np.array([2,5,8,6])

In [79]:
q = p #note that it is not a copy, it is also other name.

In [80]:
q[0] = 100

In [81]:
q

array([100,   5,   8,   6])

In [82]:
p

array([100,   5,   8,   6])

In [245]:
#use .copy()
q = p.copy()
q


array([100,   5,   8,   6])

In [246]:
q[0] = 2

In [83]:
q


array([100,   5,   8,   6])

In [84]:
p

array([100,   5,   8,   6])